services:
  qdrant:
    image: qdrant/qdrant:v1.16.3
    container_name: qdrant
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    restart: unless-stopped
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      web:
        aliases:
          - qdrant

networks:
  web:
    external: true

volumes:
  qdrant_data:
    external: true
    name: qdrant_data
